[project]
name = "tedx-bknd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django==4.2.*",
    "django-filter>=25.1",
    "djangorestframework>=3.16.1",
]
